language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --prefer-source

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit --coverage-clover build/logs/clover.xml --configuration phpunit.xml tests

after_script:
  - php vendor/bin/coveralls -v
  - CODACY_PROJECT_TOKEN="a0cbed308f0b4ad7b639c860d0c9950f" php vendor/bin/codacycoverage clover build/logs/clover.xml
